// RuoYi-Vue3-FastAPI/ruoyi-fastapi-frontend/src/views/testing/components/AIGenerateDialog.vue
<template>
  <el-dialog
    v-model="visible"
    title="AI 生成测试用例"
    width="700px"
    :close-on-click-modal="false"
    @close="handleClose"
  >
    <!-- 头部信息 -->
    <div class="dialog-header">
      <div class="header-icon">
        <el-icon :size="24"><MagicStick /></el-icon>
      </div>
      <div class="header-text">
        <h3>AI 生成测试用例</h3>
        <p>使用自然语言描述功能需求，AI 将自动生成完整的测试用例</p>
      </div>
    </div>

    <!-- 安全提示 -->
    <el-alert type="success" :closable="false" class="mb-4">
      <template #title>
        <el-icon><CircleCheck /></el-icon>
        您的数据是安全的，不会用于 AI 训练
      </template>
    </el-alert>

    <!-- 快捷建议 -->
    <div class="quick-suggestions mb-4">
      <span class="label">试试这些：</span>
      <el-button
        v-for="(item, index) in quickSuggestions"
        :key="index"
        size="small"
        @click="applyQuickSuggestion(item)"
      >
        <el-icon><MagicStick /></el-icon>
        {{ item.label }}
      </el-button>
    </div>

    <!-- 表单 -->
    <el-form ref="formRef" :model="form" :rules="rules" label-width="130px">
      <el-form-item label="功能描述" prop="prompt" required>
        <el-input
          v-model="form.prompt"
          type="textarea"
          :rows="6"
          placeholder="例如：用户登录功能，包括用户名密码验证、记住密码、忘记密码、第三方登录等场景..."
          :maxlength="2000"
          show-word-limit
        />
        <div class="form-tip">
          <el-icon><InfoFilled /></el-icon>
          描述越详细，生成的测试用例越准确。可以包含功能描述、业务场景、边界条件等信息。
        </div>
      </el-form-item>

      <el-form-item label="启用 RAG 检索">
        <el-switch v-model="form.useRag" />
        <div class="form-tip" style="margin-top: 8px">
          <el-icon><InfoFilled /></el-icon>
          启用后，AI 会先从知识库检索相关的接口文档、测试数据等信息，然后基于这些上下文生成更准确的测试用例。适用于已有文档的 API 接口测试。
        </div>
      </el-form-item>

      <el-row :gutter="20">
        <el-col :span="12">
          <el-form-item label="测试用例模板" prop="template">
            <el-select v-model="form.template" style="width: 100%">
              <el-option value="test_case">
                <div class="template-option">
                  <span class="template-name">测试步骤模板</span>
                  <span class="template-desc">传统的步骤-预期结果格式</span>
                </div>
              </el-option>
              <el-option value="test_case_bdd">
                <div class="template-option">
                  <span class="template-name">BDD 模板</span>
                  <span class="template-desc">Given-When-Then 格式</span>
                </div>
              </el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="生成数量" prop="count">
            <el-input-number
              v-model="form.count"
              :min="1"
              :max="20"
              style="width: 100%"
            />
            <div class="form-tip">建议生成 3-10 个测试用例</div>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>

    <template #footer>
      <el-button @click="handleClose">取消</el-button>
      <el-button
        type="primary"
        :loading="generating"
        :disabled="!form.prompt.trim()"
        @click="handleGenerate"
      >
        <el-icon v-if="!generating"><MagicStick /></el-icon>
        {{ generating ? 'AI 生成中...' : '生成测试用例' }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup>
import { ref, reactive, computed, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { MagicStick, CircleCheck, InfoFilled } from '@element-plus/icons-vue'

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  projectId: { type: Number, default: null },
  folderId: { type: Number, default: null }
})

const emit = defineEmits(['update:modelValue', 'open-chat', 'success'])

// 对话框可见性
const visible = computed({
  get: () => props.modelValue,
  set: (val) => emit('update:modelValue', val)
})

// 表单引用
const formRef = ref(null)

// 状态
const generating = ref(false)

// 表单数据
const form = reactive({
  prompt: '',
  template: 'test_case',
  count: 5,
  useRag: false
})

// 表单验证规则
const rules = {
  prompt: [
    { required: true, message: '请输入功能描述', trigger: 'blur' },
    { min: 5, message: '描述至少需要5个字符', trigger: 'blur' }
  ]
}

// 快捷建议
const quickSuggestions = [
  {
    label: '为用户登录生成测试用例',
    prompt: '为用户登录功能生成测试用例，包括用户名密码验证、记住密码、忘记密码、第三方登录等场景'
  },
  {
    label: '为密码重置生成测试用例',
    prompt: '为密码重置功能生成测试用例，包括邮箱验证、验证码验证、密码强度检查、重置成功后的登录等场景'
  }
]

// 应用快捷建议
const applyQuickSuggestion = (item) => {
  form.prompt = item.prompt
}

  // 生成测试用例
  const handleGenerate = async () => {
    const valid = await formRef.value?.validate()
    if (!valid) return

    // 构建聊天提示词，交给AI对话界面处理
    // 如果启用了 RAG，在 prompt 中明确要求使用 RAG 检索
    const ragInstruction = form.useRag 
      ? '\n\n⚠️ 重要：用户已明确要求使用 RAG 检索功能。请务必先调用 rag_query_tool 从知识库检索相关信息，然后基于检索结果生成测试用例。'
      : ''
    
    const chatPrompt = `请帮我生成测试用例。

需求描述：
${form.prompt.trim()}

生成数量：${form.count} 个
模板类型：${form.template === 'test_case' ? '标准测试用例' : 'BDD测试用例'}
使用 RAG 检索：${form.useRag ? '是' : '否'}${ragInstruction}

请根据以上需求生成测试用例。`

    // 触发打开AI聊天，传递 prompt、projectId 和 useRag
    emit('open-chat', {
      prompt: chatPrompt,
      projectId: props.projectId,
      useRag: form.useRag
    })
    
    // 重置表单
    resetForm()
    
    // 关闭对话框
    visible.value = false
  }

// 重置表单
const resetForm = () => {
  form.prompt = ''
  form.template = 'test_case'
  form.count = 5
  form.useRag = false
}

// 关闭对话框
const handleClose = () => {
  visible.value = false
}

// 监听对话框打开
watch(visible, (val) => {
  if (!val) {
    resetForm()
  }
})
</script>

<style scoped lang="scss">
.dialog-header {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  margin-bottom: 20px;

  .header-icon {
    width: 48px;
    height: 48px;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
  }

  .header-text {
    flex: 1;

    h3 {
      margin: 0 0 4px 0;
      font-size: 18px;
      font-weight: 600;
    }

    p {
      margin: 0;
      font-size: 14px;
      color: #909399;
    }
  }
}

.quick-suggestions {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;

  .label {
    font-size: 14px;
    color: #606266;
    font-weight: 500;
  }

  .el-button {
    border-radius: 16px;
  }
}

.form-tip {
  display: flex;
  align-items: flex-start;
  gap: 4px;
  font-size: 12px;
  color: #909399;
  margin-top: 4px;
  line-height: 1.5;

  .el-icon {
    margin-top: 2px;
    color: #409eff;
  }
}

.template-option {
  display: flex;
  flex-direction: column;

  .template-name {
    font-weight: 500;
  }

  .template-desc {
    font-size: 12px;
    color: #909399;
  }
}

:deep(.el-alert__content) {
  display: flex;
  align-items: center;
  gap: 8px;
}
</style>

// ai-test-management/ui/components/test-cases/ai-generate-dialog.tsx

// @ts-ignore  MC80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2YkVWcE5nPT06ZDc5ZGEyYjE=

"use client";
// NOTE  MS80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2YkVWcE5nPT06ZDc5ZGEyYjE=

import * as React from "react";
import { Sparkles, Loader2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { generateTestCasesFromPrompt } from "@/lib/api/ai";
import type { TestCaseInfo, TestCaseTemplate } from "@/lib/api/types";

interface AIGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectId: string;
  folderId?: string | null;
  onSuccess?: (testCases: TestCaseInfo[]) => void;
  onOpenChat?: (prompt: string) => void;
}
// eslint-disable  Mi80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2YkVWcE5nPT06ZDc5ZGEyYjE=

export function AIGenerateDialog({
  open,
  onOpenChange,
  projectId,
  folderId,
  onSuccess,
  onOpenChat,
}: AIGenerateDialogProps) {
  const [prompt, setPrompt] = React.useState("");
  const [count, setCount] = React.useState(5);
  const [template, setTemplate] = React.useState<TestCaseTemplate>("test_case");
  const [useRag, setUseRag] = React.useState(false);
  const [generating, setGenerating] = React.useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast.error("请输入生成提示词");
      return;
    }

    // 如果提供了 onOpenChat 回调，使用聊天界面
    if (onOpenChat) {
      const chatPrompt = `请帮我生成测试用例。

需求描述：
${prompt.trim()}

生成数量：${count} 个
模板类型：${template === "test_case" ? "标准测试用例" : template === "test_case_bdd" ? "BDD测试用例" : "其他"}
${useRag ? "使用 RAG 检索：是（请先从知识库检索相关上下文信息）" : "使用 RAG 检索：否"}
${folderId ? `目标文件夹ID：${folderId}` : ""}

请根据以上需求生成测试用例。${useRag ? "注意：请先使用 rag_query_tool 从知识库检索相关信息，然后基于检索结果生成测试用例。" : ""}`;

      onOpenChat(chatPrompt);
      setPrompt("");
      setUseRag(false);
      return;
    }

    // 否则使用原来的 API 方式
    try {
      setGenerating(true);
      const response = await generateTestCasesFromPrompt(projectId, {
        prompt: prompt.trim(),
        folder_id: folderId,
        count,
        template,
      });

      if (response.success && response.test_cases.length > 0) {
        toast.success(`成功生成 ${response.test_cases.length} 个测试用例`);
        onSuccess?.(response.test_cases);
        onOpenChange(false);
        setPrompt("");
      } else {
        toast.error(response.message || "生成测试用例失败");
      }
    } catch (error) {
      console.error("Failed to generate test cases:", error);
      toast.error("生成测试用例失败，请稍后重试");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Sparkles className="h-5 w-5 text-primary" />
            AI 生成测试用例
          </DialogTitle>
          <DialogDescription className="text-base">
            使用自然语言描述功能需求，AI 将自动生成完整的测试用例
          </DialogDescription>

          {/* 安全提示 */}
          <div className="flex items-center gap-2 rounded-lg bg-green-50 px-3 py-2 text-sm text-green-700 mt-3">
            <svg className="h-4 w-4 shrink-0" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
            </svg>
            <span>您的数据是安全的，不会用于 AI 训练</span>
          </div>
        </DialogHeader>

        <div className="space-y-5 py-4">
          {/* 快捷建议 */}
          <div className="space-y-2">
            <Label className="text-sm font-medium">试试这些：</Label>
            <div className="flex flex-wrap gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="h-auto py-2 px-3 text-xs"
                onClick={() => setPrompt("为用户登录功能生成测试用例，包括用户名密码验证、记住密码、忘记密码、第三方登录等场景")}
              >
                <Sparkles className="h-3 w-3 mr-1" />
                为用户登录生成测试用例
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="h-auto py-2 px-3 text-xs"
                onClick={() => setPrompt("为密码重置功能生成测试用例，包括邮箱验证、验证码验证、密码强度检查、重置成功后的登录等场景")}
              >
                <Sparkles className="h-3 w-3 mr-1" />
                为密码重置生成测试用例
              </Button>
            </div>
          </div>
          {/* 提示词输入 */}
          <div className="space-y-2">
            <Label htmlFor="prompt" className="text-sm font-medium">
              描述您想要测试的功能 <span className="text-destructive">*</span>
            </Label>
            <Textarea
              id="prompt"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="例如：用户登录功能，包括用户名密码验证、记住密码、忘记密码、第三方登录等场景..."
              rows={6}
              className="resize-none"
            />
            <p className="text-xs text-muted-foreground flex items-start gap-1">
              <span className="text-primary">💡</span>
              <span>描述越详细，生成的测试用例越准确。可以包含功能描述、业务场景、边界条件等信息。</span>
            </p>
          </div>

          {/* RAG 检索选项 */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="useRag" className="text-sm font-medium">启用 RAG 上下文检索</Label>
              <input
                id="useRag"
                type="checkbox"
                checked={useRag}
                onChange={(e) => setUseRag(e.target.checked)}
                className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
              />
            </div>
            <p className="text-xs text-muted-foreground flex items-start gap-1">
              <span className="text-primary">💡</span>
              <span>
                启用后，AI 会先从知识库检索相关的接口文档、测试数据等信息，
                然后基于这些上下文生成更准确的测试用例。
                适用于已有文档的 API 接口测试。
              </span>
            </p>
          </div>

          {/* 配置选项 */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="template" className="text-sm font-medium">测试用例模板</Label>
              <Select
                value={template}
                onValueChange={(v) => setTemplate(v as TestCaseTemplate)}
              >
                <SelectTrigger id="template" className="h-10">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="test_case">
                    <div className="flex flex-col items-start">
                      <span className="font-medium">测试步骤模板</span>
                      <span className="text-xs text-muted-foreground">传统的步骤-预期结果格式</span>
                    </div>
                  </SelectItem>
                  <SelectItem value="test_case_bdd">
                    <div className="flex flex-col items-start">
                      <span className="font-medium">BDD 模板</span>
                      <span className="text-xs text-muted-foreground">Given-When-Then 格式</span>
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="count" className="text-sm font-medium">生成数量</Label>
              <Input
                id="count"
                type="number"
                min={1}
                max={20}
                value={count}
                onChange={(e) => setCount(parseInt(e.target.value) || 5)}
                className="h-10"
              />
              <p className="text-xs text-muted-foreground">
                建议生成 3-10 个测试用例
              </p>
            </div>
          </div>
        </div>

        <DialogFooter className="gap-2">
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={generating}
            className="min-w-[100px]"
          >
            取消
          </Button>
          <Button
            onClick={handleGenerate}
            disabled={generating || !prompt.trim()}
            className="min-w-[140px]"
          >
            {generating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                AI 生成中...
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                生成测试用例
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// NOTE  My80OmFIVnBZMlhwZ3JIa3VwSHBuSjQ2YkVWcE5nPT06ZDc5ZGEyYjE=
